services:
  clisimplehub-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clisimplehub-server
    ports:
      - '${PORT:-5600}:5600'
      - '${CLASH_SOCKS_PORT:-10808}:${CLASH_SOCKS_PORT:-10808}'
    environment:
      PORT: '${PORT:-5600}'
      LISTEN_ADDR: '${LISTEN_ADDR:-0.0.0.0}'
      DATA: '/data'
      CLASH_SOCKS_LISTEN: '${CLASH_SOCKS_LISTEN:-0.0.0.0}'
      CLASH_SOCKS_PORT: '${CLASH_SOCKS_PORT:-10808}'
      API_KEY: '${API_KEY:-abcd1234}'
    volumes:
      - ./data:/data
    restart: unless-stopped
