package shared

import (
	"clisimplehub/internal/dbconfig"
	"clisimplehub/internal/sqlitequeue"
	"context"
	"database/sql"
	_ "embed"
	"errors"
	"fmt"
	"math"
	"strings"
	"time"
)

//go:embed codex_schema.sql
var codexSchemaSQL string

const pgCodexSchemaSQL = `
CREATE TABLE IF NOT EXISTS codex_accounts (
    id             TEXT PRIMARY KEY,
    account_id     TEXT NOT NULL DEFAULT '',
    refresh_token  TEXT NOT NULL DEFAULT '',
    access_token   TEXT NOT NULL DEFAULT '',
    id_token       TEXT NOT NULL DEFAULT '',
    email          TEXT NOT NULL DEFAULT '',
    plan_type      TEXT NOT NULL DEFAULT '',
    enabled        INTEGER NOT NULL DEFAULT 1,
    websockets     INTEGER NOT NULL DEFAULT 1,
    password       TEXT NOT NULL DEFAULT '',
    mfa_code       TEXT NOT NULL DEFAULT '',
    expires_at     TIMESTAMPTZ,
    status         TEXT NOT NULL DEFAULT 'valid',
    weight         INTEGER NOT NULL DEFAULT 1,
    proxy_url      TEXT NOT NULL DEFAULT '',
    cooldown_until TIMESTAMPTZ,
    cooldown_reason TEXT NOT NULL DEFAULT '',
    usage_primary_used_pct           DOUBLE PRECISION NOT NULL DEFAULT 0,
    usage_primary_reset_secs         INTEGER NOT NULL DEFAULT 0,
    usage_primary_window_mins        INTEGER NOT NULL DEFAULT 0,
    usage_secondary_used_pct         DOUBLE PRECISION NOT NULL DEFAULT 0,
    usage_secondary_reset_secs       INTEGER NOT NULL DEFAULT 0,
    usage_secondary_window_mins      INTEGER NOT NULL DEFAULT 0,
    usage_primary_over_secondary_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    usage_reset_credits_available_count INTEGER NOT NULL DEFAULT 0,
    usage_updated_at                 TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS codex_account_stats (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      TEXT NOT NULL,
    account_email   TEXT NOT NULL DEFAULT '',
    model           TEXT NOT NULL DEFAULT '',
    date            TEXT NOT NULL,
    hour            INTEGER NOT NULL DEFAULT 0,
    input_tokens    BIGINT NOT NULL DEFAULT 0,
    output_tokens   BIGINT NOT NULL DEFAULT 0,
    total_tokens    BIGINT NOT NULL DEFAULT 0,
    cached_tokens   BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens BIGINT NOT NULL DEFAULT 0,
    cache_creation_tokens BIGINT NOT NULL DEFAULT 0,
    reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    status_code     INTEGER NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'unknown',
    error_type      TEXT NOT NULL DEFAULT '',
    duration_ms     BIGINT NOT NULL DEFAULT 0,
    ttft_ms         BIGINT NOT NULL DEFAULT 0,
    executor_type   TEXT NOT NULL DEFAULT '',
    requested_model TEXT NOT NULL DEFAULT '',
    source          TEXT NOT NULL DEFAULT '',
    reasoning_effort TEXT NOT NULL DEFAULT '',
    service_tier    TEXT NOT NULL DEFAULT '',
    response_service_tier TEXT NOT NULL DEFAULT '',
    additional_model INTEGER NOT NULL DEFAULT 0,
    primary_used_pct     DOUBLE PRECISION,
    secondary_used_pct   DOUBLE PRECISION,
    request_path    TEXT NOT NULL DEFAULT '',
    create_time     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS codex_model_prices (
    model                   TEXT PRIMARY KEY,
    input_per_1m            DOUBLE PRECISION NOT NULL,
    cached_input_per_1m     DOUBLE PRECISION NOT NULL,
    cache_write_per_1m      DOUBLE PRECISION NOT NULL,
    output_per_1m           DOUBLE PRECISION NOT NULL,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS codex_store_metadata (
    meta_key                TEXT PRIMARY KEY,
    value                   TEXT NOT NULL DEFAULT '',
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_codex_accounts_refresh_token ON codex_accounts(refresh_token);
CREATE INDEX IF NOT EXISTS idx_codex_accounts_account_id ON codex_accounts(account_id);
CREATE INDEX IF NOT EXISTS idx_codex_stats_account_date ON codex_account_stats(account_id, date);
CREATE INDEX IF NOT EXISTS idx_codex_stats_date ON codex_account_stats(date);
`

const createCodexAccountsTableSQL = `
CREATE TABLE codex_accounts (
    id             TEXT PRIMARY KEY,
    account_id     TEXT NOT NULL DEFAULT '',
    refresh_token  TEXT NOT NULL DEFAULT '',
    access_token   TEXT NOT NULL DEFAULT '',
    id_token       TEXT NOT NULL DEFAULT '',
    email          TEXT NOT NULL DEFAULT '',
    plan_type      TEXT NOT NULL DEFAULT '',
    enabled        INTEGER NOT NULL DEFAULT 1,
    websockets     INTEGER NOT NULL DEFAULT 1,
    password       TEXT NOT NULL DEFAULT '',
    mfa_code       TEXT NOT NULL DEFAULT '',
    expires_at     DATETIME,
    status         TEXT NOT NULL DEFAULT 'valid',
    weight         INTEGER NOT NULL DEFAULT 1,
    proxy_url      TEXT NOT NULL DEFAULT '',
    cooldown_until DATETIME,
    cooldown_reason TEXT NOT NULL DEFAULT '',
    usage_primary_used_pct           REAL NOT NULL DEFAULT 0,
    usage_primary_reset_secs         INTEGER NOT NULL DEFAULT 0,
    usage_primary_window_mins        INTEGER NOT NULL DEFAULT 0,
    usage_secondary_used_pct         REAL NOT NULL DEFAULT 0,
    usage_secondary_reset_secs       INTEGER NOT NULL DEFAULT 0,
    usage_secondary_window_mins      INTEGER NOT NULL DEFAULT 0,
    usage_primary_over_secondary_pct REAL NOT NULL DEFAULT 0,
    usage_reset_credits_available_count INTEGER NOT NULL DEFAULT 0,
    usage_updated_at                 DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)`

type SQLiteCodexAccountStore struct {
	db      *sql.DB
	queue   *sqlitequeue.Manager
	driver  string
	closeDB bool
}

func OpenCodexAccountStore(dbPath string) (*SQLiteCodexAccountStore, error) {
	return OpenCodexAccountStoreWithConfig(dbconfig.Config{Driver: dbconfig.DriverSQLite, Source: dbPath})
}

func OpenCodexAccountStoreWithConfig(cfg dbconfig.Config) (*SQLiteCodexAccountStore, error) {
	switch cfg.Driver {
	case dbconfig.DriverSQLite:
		return openSQLiteCodexAccountStore(cfg.Source)
	case dbconfig.DriverPGX:
		return openPGXCodexAccountStore(cfg.Source)
	default:
		return nil, fmt.Errorf("unsupported codex account db driver: %s", cfg.Driver)
	}
}

func openSQLiteCodexAccountStore(dbPath string) (*SQLiteCodexAccountStore, error) {
	queue, err := sqlitequeue.Open(dbPath)
	if err != nil {
		return nil, err
	}

	s := &SQLiteCodexAccountStore{
		db:     queue.DB(),
		queue:  queue,
		driver: dbconfig.DriverSQLite,
	}
	if err := s.initSchema(context.Background()); err != nil {
		_ = queue.Close()
		return nil, err
	}
	return s, nil
}

func openPGXCodexAccountStore(source string) (*SQLiteCodexAccountStore, error) {
	db, err := dbconfig.OpenSQL(dbconfig.Config{Driver: dbconfig.DriverPGX, Source: source})
	if err != nil {
		return nil, err
	}
	s := &SQLiteCodexAccountStore{
		db:      db,
		driver:  dbconfig.DriverPGX,
		closeDB: true,
	}
	if err := s.initSchema(context.Background()); err != nil {
		_ = db.Close()
		return nil, err
	}
	return s, nil
}

func (s *SQLiteCodexAccountStore) initSchema(ctx context.Context) error {
	if s == nil || s.db == nil {
		return errors.New("nil codex account store")
	}
	schema := codexSchemaSQL
	if s.driver == dbconfig.DriverPGX {
		schema = pgCodexSchemaSQL
	}
	if err := s.execScript(ctx, schema); err != nil {
		return fmt.Errorf("apply codex schema: %w", err)
	}
	if err := s.ensureAccountCapabilityColumns(ctx); err != nil {
		return err
	}
	if err := s.ensureCodexAccountStatsUsageColumns(ctx); err != nil {
		return err
	}
	if err := s.initializeDefaultModelPrices(ctx); err != nil {
		return err
	}
	if s.driver == dbconfig.DriverSQLite {
		if err := s.migrateCodexAccountsLocalID(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (s *SQLiteCodexAccountStore) execScript(ctx context.Context, script string) error {
	for _, stmt := range strings.Split(script, ";") {
		stmt = strings.TrimSpace(stmt)
		if stmt == "" {
			continue
		}
		if _, err := s.execWrite(ctx, stmt); err != nil {
			return err
		}
	}
	return nil
}

func (s *SQLiteCodexAccountStore) execWrite(ctx context.Context, query string, args ...any) (sql.Result, error) {
	query = s.rebind(query)
	if s.queue != nil {
		return s.queue.ExecWrite(ctx, query, args...)
	}
	return s.db.ExecContext(ctx, query, args...)
}

func (s *SQLiteCodexAccountStore) withTx(ctx context.Context, fn func(context.Context, *sql.Tx) error) error {
	if s.queue != nil {
		return s.queue.WithTx(ctx, fn)
	}
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	committed := false
	defer func() {
		if !committed {
			_ = tx.Rollback()
		}
	}()
	if err := fn(ctx, tx); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	committed = true
	return nil
}

func (s *SQLiteCodexAccountStore) queryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	return s.db.QueryContext(ctx, s.rebind(query), args...)
}

func (s *SQLiteCodexAccountStore) queryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	return s.db.QueryRowContext(ctx, s.rebind(query), args...)
}

func (s *SQLiteCodexAccountStore) rebind(query string) string {
	if s == nil || s.driver != dbconfig.DriverPGX {
		return query
	}
	return dbconfig.RebindPostgres(query)
}

func (s *SQLiteCodexAccountStore) placeholders(count int) string {
	return dbconfig.Placeholders(s.driver, count)
}

func (s *SQLiteCodexAccountStore) migrateCodexAccountsLocalID(ctx context.Context) error {
	columns, err := s.codexAccountColumns(ctx)
	if err != nil {
		return err
	}
	if columns["id"] {
		return nil
	}

	return s.queue.WithTx(ctx, func(txCtx context.Context, tx *sql.Tx) error {
		if _, err := tx.ExecContext(txCtx, `ALTER TABLE codex_accounts RENAME TO codex_accounts_legacy_account_id_pk`); err != nil {
			return fmt.Errorf("rename legacy codex_accounts: %w", err)
		}
		if _, err := tx.ExecContext(txCtx, createCodexAccountsTableSQL); err != nil {
			return fmt.Errorf("create migrated codex_accounts: %w", err)
		}

		rows, err := tx.QueryContext(txCtx, `
			SELECT account_id, refresh_token, access_token, id_token, email, plan_type,
			       enabled, websockets, password, mfa_code, expires_at, status, weight, proxy_url,
			       cooldown_until, cooldown_reason,
			       usage_primary_used_pct, usage_primary_reset_secs, usage_primary_window_mins,
			       usage_secondary_used_pct, usage_secondary_reset_secs, usage_secondary_window_mins,
			       usage_primary_over_secondary_pct, usage_reset_credits_available_count, usage_updated_at,
			       created_at, updated_at
			FROM codex_accounts_legacy_account_id_pk`)
		if err != nil {
			return fmt.Errorf("read legacy codex accounts: %w", err)
		}
		defer rows.Close()

		legacyIDMap := make(map[string]string)
		for rows.Next() {
			a, err := scanLegacyAccount(rows)
			if err != nil {
				return err
			}
			localID := GenerateCodexLocalID(a.AccountID, a.Email)
			if localID == "" {
				localID = strings.TrimSpace(a.AccountID)
			}
			if localID == "" {
				return fmt.Errorf("legacy codex account missing account_id")
			}
			a.ID = localID
			if _, exists := legacyIDMap[a.AccountID]; !exists {
				legacyIDMap[a.AccountID] = localID
			}
			if err := insertCodexAccountTx(txCtx, tx, a); err != nil {
				return fmt.Errorf("migrate account %q: %w", a.AccountID, err)
			}
		}
		if err := rows.Err(); err != nil {
			return err
		}

		for legacyID, localID := range legacyIDMap {
			if _, err := tx.ExecContext(txCtx, `UPDATE codex_account_stats SET account_id = ? WHERE account_id = ?`, localID, legacyID); err != nil {
				return fmt.Errorf("migrate stats account id: %w", err)
			}
		}
		if _, err := tx.ExecContext(txCtx, `DROP TABLE codex_accounts_legacy_account_id_pk`); err != nil {
			return fmt.Errorf("drop legacy codex_accounts: %w", err)
		}
		if _, err := tx.ExecContext(txCtx, `CREATE INDEX IF NOT EXISTS idx_codex_accounts_refresh_token ON codex_accounts(refresh_token)`); err != nil {
			return fmt.Errorf("create refresh token index: %w", err)
		}
		if _, err := tx.ExecContext(txCtx, `CREATE INDEX IF NOT EXISTS idx_codex_accounts_account_id ON codex_accounts(account_id)`); err != nil {
			return fmt.Errorf("create account id index: %w", err)
		}
		return nil
	})
}

func insertCodexAccountTx(ctx context.Context, tx *sql.Tx, a *CodexAccount) error {
	if a == nil {
		return errors.New("nil account")
	}
	EnsureCodexLocalID(a)
	if strings.TrimSpace(a.ID) == "" {
		a.ID = strings.TrimSpace(a.AccountID)
	}
	if strings.TrimSpace(a.ID) == "" {
		return fmt.Errorf("account id is required")
	}

	var usagePrimPct, usageSecPct, usagePriOverSec float64
	var usagePrimReset, usagePrimWin, usageSecReset, usageSecWin, usageResetCredits int
	var usageUpdatedAt any
	if a.CodexUsage != nil {
		usagePrimPct = a.CodexUsage.PrimaryUsedPercent
		usagePrimReset = a.CodexUsage.PrimaryResetAfterSeconds
		usagePrimWin = a.CodexUsage.PrimaryWindowMinutes
		usageSecPct = a.CodexUsage.SecondaryUsedPercent
		usageSecReset = a.CodexUsage.SecondaryResetAfterSeconds
		usageSecWin = a.CodexUsage.SecondaryWindowMinutes
		usagePriOverSec = a.CodexUsage.PrimaryOverSecondaryPercent
		usageResetCredits = a.CodexUsage.ResetCreditsAvailableCount
		if !a.CodexUsage.UpdatedAt.IsZero() {
			usageUpdatedAt = sqliteTime(a.CodexUsage.UpdatedAt)
		}
	}

	_, err := tx.ExecContext(ctx, `
		INSERT INTO codex_accounts (
			id, account_id, refresh_token, access_token, id_token, email, plan_type,
			enabled, websockets, password, mfa_code, expires_at, status, weight, proxy_url,
			cooldown_until, cooldown_reason,
			usage_primary_used_pct, usage_primary_reset_secs, usage_primary_window_mins,
			usage_secondary_used_pct, usage_secondary_reset_secs, usage_secondary_window_mins,
			usage_primary_over_secondary_pct, usage_reset_credits_available_count, usage_updated_at,
			created_at, updated_at
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		a.ID, a.AccountID, a.RefreshToken, a.AccessToken, a.IDToken, a.Email, a.PlanType,
		boolToInt(a.Enabled), boolToInt(a.Websockets),
		a.Password, a.MFACode,
		nullTime(a.ExpiresAt), string(a.Status), a.EffectiveWeight(), a.ProxyUrl,
		nullTime(a.CooldownUntil), a.CooldownReason,
		usagePrimPct, usagePrimReset, usagePrimWin,
		usageSecPct, usageSecReset, usageSecWin,
		usagePriOverSec, usageResetCredits, usageUpdatedAt,
		sqliteTime(a.CreatedAt), sqliteTime(a.UpdatedAt),
	)
	return err
}

func (s *SQLiteCodexAccountStore) ensureAccountCapabilityColumns(ctx context.Context) error {
	columns, err := s.tableColumns(ctx, "codex_accounts")
	if err != nil {
		return err
	}
	if !columns["enabled"] {
		if _, err := s.execWrite(ctx, `ALTER TABLE codex_accounts ADD COLUMN enabled INTEGER NOT NULL DEFAULT 1`); err != nil {
			return fmt.Errorf("add codex_accounts.enabled: %w", err)
		}
	}
	if !columns["websockets"] {
		if _, err := s.execWrite(ctx, `ALTER TABLE codex_accounts ADD COLUMN websockets INTEGER NOT NULL DEFAULT 0`); err != nil {
			return fmt.Errorf("add codex_accounts.websockets: %w", err)
		}
	}
	if !columns["usage_reset_credits_available_count"] {
		if _, err := s.execWrite(ctx, `ALTER TABLE codex_accounts ADD COLUMN usage_reset_credits_available_count INTEGER NOT NULL DEFAULT 0`); err != nil {
			return fmt.Errorf("add codex_accounts.usage_reset_credits_available_count: %w", err)
		}
	}
	return nil
}

func (s *SQLiteCodexAccountStore) codexAccountColumns(ctx context.Context) (map[string]bool, error) {
	return s.tableColumns(ctx, "codex_accounts")
}

func (s *SQLiteCodexAccountStore) ensureCodexAccountStatsUsageColumns(ctx context.Context) error {
	columns, err := s.tableColumns(ctx, "codex_account_stats")
	if err != nil {
		return err
	}
	columnType := "INTEGER"
	if s.driver == dbconfig.DriverPGX {
		columnType = "BIGINT"
	}
	for _, column := range []string{"cached_tokens", "cache_read_tokens", "cache_creation_tokens", "reasoning_tokens", "additional_model"} {
		if columns[column] {
			continue
		}
		if _, err := s.execWrite(ctx, fmt.Sprintf(`ALTER TABLE codex_account_stats ADD COLUMN %s %s NOT NULL DEFAULT 0`, column, columnType)); err != nil {
			return fmt.Errorf("add codex_account_stats.%s: %w", column, err)
		}
	}
	if !columns["ttft_ms"] {
		if _, err := s.execWrite(ctx, fmt.Sprintf(`ALTER TABLE codex_account_stats ADD COLUMN ttft_ms %s NOT NULL DEFAULT 0`, columnType)); err != nil {
			return fmt.Errorf("add codex_account_stats.ttft_ms: %w", err)
		}
	}
	for _, column := range []string{"executor_type", "requested_model", "source", "reasoning_effort", "service_tier", "response_service_tier"} {
		if columns[column] {
			continue
		}
		if _, err := s.execWrite(ctx, fmt.Sprintf(`ALTER TABLE codex_account_stats ADD COLUMN %s TEXT NOT NULL DEFAULT ''`, column)); err != nil {
			return fmt.Errorf("add codex_account_stats.%s: %w", column, err)
		}
	}
	return nil
}

func (s *SQLiteCodexAccountStore) tableColumns(ctx context.Context, tableName string) (map[string]bool, error) {
	columns := make(map[string]bool)
	if s.driver == dbconfig.DriverPGX {
		rows, err := s.db.QueryContext(ctx, `
SELECT column_name
FROM information_schema.columns
WHERE table_schema = current_schema()
  AND table_name = $1`, tableName)
		if err != nil {
			return nil, fmt.Errorf("inspect %s columns: %w", tableName, err)
		}
		defer rows.Close()

		for rows.Next() {
			var name string
			if err := rows.Scan(&name); err != nil {
				return nil, err
			}
			columns[strings.ToLower(strings.TrimSpace(name))] = true
		}
		return columns, rows.Err()
	}

	rows, err := s.db.QueryContext(ctx, fmt.Sprintf(`PRAGMA table_info(%s)`, tableName))
	if err != nil {
		return nil, fmt.Errorf("inspect %s columns: %w", tableName, err)
	}
	defer rows.Close()

	for rows.Next() {
		var cid int
		var name string
		var columnType string
		var notNull int
		var defaultValue any
		var pk int
		if err := rows.Scan(&cid, &name, &columnType, &notNull, &defaultValue, &pk); err != nil {
			return nil, err
		}
		columns[strings.ToLower(strings.TrimSpace(name))] = true
	}
	return columns, rows.Err()
}

func (s *SQLiteCodexAccountStore) Close() error {
	if s == nil {
		return nil
	}
	if s.queue != nil {
		return s.queue.Close()
	}
	if s.closeDB && s.db != nil {
		return s.db.Close()
	}
	return nil
}

// --- Account CRUD ---

func (s *SQLiteCodexAccountStore) ListAccounts(ctx context.Context) ([]CodexAccount, error) {
	rows, err := s.queryContext(ctx, `
		SELECT id, account_id, refresh_token, access_token, id_token, email, plan_type,
		       enabled, websockets, password, mfa_code, expires_at, status, weight, proxy_url,
		       cooldown_until, cooldown_reason,
		       usage_primary_used_pct, usage_primary_reset_secs, usage_primary_window_mins,
		       usage_secondary_used_pct, usage_secondary_reset_secs, usage_secondary_window_mins,
		       usage_primary_over_secondary_pct, usage_reset_credits_available_count, usage_updated_at,
		       created_at, updated_at
		FROM codex_accounts ORDER BY weight DESC, created_at ASC`)
	if err != nil {
		return nil, fmt.Errorf("list accounts: %w", err)
	}
	defer rows.Close()

	var accounts []CodexAccount
	for rows.Next() {
		a, err := scanAccount(rows)
		if err != nil {
			return nil, err
		}
		accounts = append(accounts, *a)
	}
	return accounts, rows.Err()
}

func (s *SQLiteCodexAccountStore) ListAccountsPage(ctx context.Context, offset, limit int) ([]CodexAccount, error) {
	if offset < 0 {
		offset = 0
	}
	if limit <= 0 {
		limit = 20
	}

	rows, err := s.queryContext(ctx, `
		SELECT id, account_id, refresh_token, access_token, id_token, email, plan_type,
		       enabled, websockets, password, mfa_code, expires_at, status, weight, proxy_url,
		       cooldown_until, cooldown_reason,
		       usage_primary_used_pct, usage_primary_reset_secs, usage_primary_window_mins,
		       usage_secondary_used_pct, usage_secondary_reset_secs, usage_secondary_window_mins,
		       usage_primary_over_secondary_pct, usage_reset_credits_available_count, usage_updated_at,
		       created_at, updated_at
		FROM codex_accounts
		ORDER BY weight DESC, created_at ASC
		LIMIT ? OFFSET ?`, limit, offset)
	if err != nil {
		return nil, fmt.Errorf("list accounts page: %w", err)
	}
	defer rows.Close()

	var accounts []CodexAccount
	for rows.Next() {
		a, err := scanAccount(rows)
		if err != nil {
			return nil, err
		}
		accounts = append(accounts, *a)
	}
	return accounts, rows.Err()
}

func (s *SQLiteCodexAccountStore) CountAccounts(ctx context.Context) (int, error) {
	var total int
	if err := s.queryRowContext(ctx, `SELECT COUNT(1) FROM codex_accounts`).Scan(&total); err != nil {
		return 0, fmt.Errorf("count accounts: %w", err)
	}
	return total, nil
}

func (s *SQLiteCodexAccountStore) GetByID(ctx context.Context, accountID string) (*CodexAccount, error) {
	row := s.queryRowContext(ctx, `
		SELECT id, account_id, refresh_token, access_token, id_token, email, plan_type,
		       enabled, websockets, password, mfa_code, expires_at, status, weight, proxy_url,
		       cooldown_until, cooldown_reason,
		       usage_primary_used_pct, usage_primary_reset_secs, usage_primary_window_mins,
		       usage_secondary_used_pct, usage_secondary_reset_secs, usage_secondary_window_mins,
		       usage_primary_over_secondary_pct, usage_reset_credits_available_count, usage_updated_at,
		       created_at, updated_at
		FROM codex_accounts WHERE id = ?`, accountID)
	return scanAccountRow(row)
}

func (s *SQLiteCodexAccountStore) GetByRefreshToken(ctx context.Context, rt string) (*CodexAccount, error) {
	row := s.queryRowContext(ctx, `
		SELECT id, account_id, refresh_token, access_token, id_token, email, plan_type,
		       enabled, websockets, password, mfa_code, expires_at, status, weight, proxy_url,
		       cooldown_until, cooldown_reason,
		       usage_primary_used_pct, usage_primary_reset_secs, usage_primary_window_mins,
		       usage_secondary_used_pct, usage_secondary_reset_secs, usage_secondary_window_mins,
		       usage_primary_over_secondary_pct, usage_reset_credits_available_count, usage_updated_at,
		       created_at, updated_at
		FROM codex_accounts WHERE refresh_token = ?`, rt)
	return scanAccountRow(row)
}

func (s *SQLiteCodexAccountStore) Insert(ctx context.Context, a *CodexAccount) error {
	if a == nil {
		return errors.New("nil account")
	}
	EnsureCodexLocalID(a)
	if strings.TrimSpace(a.ID) == "" {
		a.ID = strings.TrimSpace(a.AccountID)
	}
	if strings.TrimSpace(a.ID) == "" {
		return fmt.Errorf("account id is required")
	}
	now := time.Now()
	if a.CreatedAt.IsZero() {
		a.CreatedAt = now
	}
	if a.UpdatedAt.IsZero() {
		a.UpdatedAt = now
	}

	var usagePrimPct, usageSecPct, usagePriOverSec float64
	var usagePrimReset, usagePrimWin, usageSecReset, usageSecWin, usageResetCredits int
	var usageUpdatedAt any
	if a.CodexUsage != nil {
		usagePrimPct = a.CodexUsage.PrimaryUsedPercent
		usagePrimReset = a.CodexUsage.PrimaryResetAfterSeconds
		usagePrimWin = a.CodexUsage.PrimaryWindowMinutes
		usageSecPct = a.CodexUsage.SecondaryUsedPercent
		usageSecReset = a.CodexUsage.SecondaryResetAfterSeconds
		usageSecWin = a.CodexUsage.SecondaryWindowMinutes
		usagePriOverSec = a.CodexUsage.PrimaryOverSecondaryPercent
		usageResetCredits = a.CodexUsage.ResetCreditsAvailableCount
		if !a.CodexUsage.UpdatedAt.IsZero() {
			usageUpdatedAt = sqliteTime(a.CodexUsage.UpdatedAt)
		}
	}

	_, err := s.execWrite(ctx, `
		INSERT INTO codex_accounts (
			id, account_id, refresh_token, access_token, id_token, email, plan_type,
			enabled, websockets, password, mfa_code, expires_at, status, weight, proxy_url,
			cooldown_until, cooldown_reason,
			usage_primary_used_pct, usage_primary_reset_secs, usage_primary_window_mins,
			usage_secondary_used_pct, usage_secondary_reset_secs, usage_secondary_window_mins,
			usage_primary_over_secondary_pct, usage_reset_credits_available_count, usage_updated_at,
			created_at, updated_at
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		a.ID, a.AccountID, a.RefreshToken, a.AccessToken, a.IDToken, a.Email, a.PlanType,
		boolToInt(a.Enabled), boolToInt(a.Websockets),
		a.Password, a.MFACode,
		nullTime(a.ExpiresAt), string(a.Status), a.EffectiveWeight(), a.ProxyUrl,
		nullTime(a.CooldownUntil), a.CooldownReason,
		usagePrimPct, usagePrimReset, usagePrimWin,
		usageSecPct, usageSecReset, usageSecWin,
		usagePriOverSec, usageResetCredits, usageUpdatedAt,
		sqliteTime(a.CreatedAt), sqliteTime(a.UpdatedAt),
	)
	return err
}

func (s *SQLiteCodexAccountStore) Update(ctx context.Context, a *CodexAccount) error {
	if a == nil {
		return errors.New("nil account")
	}
	EnsureCodexLocalID(a)
	if strings.TrimSpace(a.ID) == "" {
		a.ID = strings.TrimSpace(a.AccountID)
	}
	if strings.TrimSpace(a.ID) == "" {
		return fmt.Errorf("account id is required")
	}
	a.UpdatedAt = time.Now()

	var usagePrimPct, usageSecPct, usagePriOverSec float64
	var usagePrimReset, usagePrimWin, usageSecReset, usageSecWin, usageResetCredits int
	var usageUpdatedAt any
	if a.CodexUsage != nil {
		usagePrimPct = a.CodexUsage.PrimaryUsedPercent
		usagePrimReset = a.CodexUsage.PrimaryResetAfterSeconds
		usagePrimWin = a.CodexUsage.PrimaryWindowMinutes
		usageSecPct = a.CodexUsage.SecondaryUsedPercent
		usageSecReset = a.CodexUsage.SecondaryResetAfterSeconds
		usageSecWin = a.CodexUsage.SecondaryWindowMinutes
		usagePriOverSec = a.CodexUsage.PrimaryOverSecondaryPercent
		usageResetCredits = a.CodexUsage.ResetCreditsAvailableCount
		if !a.CodexUsage.UpdatedAt.IsZero() {
			usageUpdatedAt = sqliteTime(a.CodexUsage.UpdatedAt)
		}
	}

	_, err := s.execWrite(ctx, `
		UPDATE codex_accounts SET
			refresh_token = ?, access_token = ?, id_token = ?, email = ?, plan_type = ?,
			enabled = ?, websockets = ?, password = ?, mfa_code = ?,
			expires_at = ?, status = ?, weight = ?, proxy_url = ?,
			cooldown_until = ?, cooldown_reason = ?,
			usage_primary_used_pct = ?, usage_primary_reset_secs = ?, usage_primary_window_mins = ?,
			usage_secondary_used_pct = ?, usage_secondary_reset_secs = ?, usage_secondary_window_mins = ?,
			usage_primary_over_secondary_pct = ?, usage_reset_credits_available_count = ?, usage_updated_at = ?,
			updated_at = ?
		WHERE id = ?`,
		a.RefreshToken, a.AccessToken, a.IDToken, a.Email, a.PlanType,
		boolToInt(a.Enabled), boolToInt(a.Websockets),
		a.Password, a.MFACode,
		nullTime(a.ExpiresAt), string(a.Status), a.EffectiveWeight(), a.ProxyUrl,
		nullTime(a.CooldownUntil), a.CooldownReason,
		usagePrimPct, usagePrimReset, usagePrimWin,
		usageSecPct, usageSecReset, usageSecWin,
		usagePriOverSec, usageResetCredits, usageUpdatedAt,
		sqliteTime(a.UpdatedAt),
		a.ID,
	)
	return err
}

func (s *SQLiteCodexAccountStore) Delete(ctx context.Context, accountID string) error {
	return s.withTx(ctx, func(txCtx context.Context, tx *sql.Tx) error {
		if _, err := tx.ExecContext(txCtx, s.rebind(`DELETE FROM codex_account_stats WHERE account_id = ?`), accountID); err != nil {
			return fmt.Errorf("delete stats: %w", err)
		}
		if _, err := tx.ExecContext(txCtx, s.rebind(`DELETE FROM codex_accounts WHERE id = ?`), accountID); err != nil {
			return fmt.Errorf("delete account: %w", err)
		}
		return nil
	})
}

func (s *SQLiteCodexAccountStore) DeleteMany(ctx context.Context, accountIDs []string) error {
	normalized := make([]string, 0, len(accountIDs))
	seen := make(map[string]struct{}, len(accountIDs))
	for _, id := range accountIDs {
		id = strings.TrimSpace(id)
		if id == "" {
			continue
		}
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		normalized = append(normalized, id)
	}
	if len(normalized) == 0 {
		return nil
	}

	placeholders := s.placeholders(len(normalized))
	args := make([]any, len(normalized))
	for i := range normalized {
		args[i] = normalized[i]
	}

	return s.withTx(ctx, func(txCtx context.Context, tx *sql.Tx) error {
		if _, err := tx.ExecContext(txCtx, `DELETE FROM codex_account_stats WHERE account_id IN (`+placeholders+`)`, args...); err != nil {
			return fmt.Errorf("delete stats: %w", err)
		}
		if _, err := tx.ExecContext(txCtx, `DELETE FROM codex_accounts WHERE id IN (`+placeholders+`)`, args...); err != nil {
			return fmt.Errorf("delete accounts: %w", err)
		}
		return nil
	})
}

// ReplaceAllAccounts replaces all codex accounts in one transaction.
// It keeps usage history for current accounts and removes orphaned stats via relational delete.
func (s *SQLiteCodexAccountStore) ReplaceAllAccounts(ctx context.Context, accounts []CodexAccount) error {
	return s.withTx(ctx, func(txCtx context.Context, tx *sql.Tx) error {
		if _, err := tx.ExecContext(txCtx, `DELETE FROM codex_accounts`); err != nil {
			return fmt.Errorf("clear accounts: %w", err)
		}

		now := time.Now()
		for i := range accounts {
			a := accounts[i]
			EnsureCodexLocalID(&a)
			if strings.TrimSpace(a.ID) == "" {
				a.ID = strings.TrimSpace(a.AccountID)
			}
			if a.ID == "" {
				return fmt.Errorf("account[%d] id is required", i)
			}
			a.AccountID = strings.TrimSpace(a.AccountID)
			if a.AccountID == "" {
				return fmt.Errorf("account[%d] account_id is required", i)
			}
			if a.CreatedAt.IsZero() {
				a.CreatedAt = now
			}
			if a.UpdatedAt.IsZero() {
				a.UpdatedAt = a.CreatedAt
			}

			var usagePrimPct, usageSecPct, usagePriOverSec float64
			var usagePrimReset, usagePrimWin, usageSecReset, usageSecWin, usageResetCredits int
			var usageUpdatedAt any
			if a.CodexUsage != nil {
				usagePrimPct = a.CodexUsage.PrimaryUsedPercent
				usagePrimReset = a.CodexUsage.PrimaryResetAfterSeconds
				usagePrimWin = a.CodexUsage.PrimaryWindowMinutes
				usageSecPct = a.CodexUsage.SecondaryUsedPercent
				usageSecReset = a.CodexUsage.SecondaryResetAfterSeconds
				usageSecWin = a.CodexUsage.SecondaryWindowMinutes
				usagePriOverSec = a.CodexUsage.PrimaryOverSecondaryPercent
				usageResetCredits = a.CodexUsage.ResetCreditsAvailableCount
				if !a.CodexUsage.UpdatedAt.IsZero() {
					usageUpdatedAt = sqliteTime(a.CodexUsage.UpdatedAt)
				}
			}

			if _, err := tx.ExecContext(txCtx, s.rebind(`
				INSERT INTO codex_accounts (
					id, account_id, refresh_token, access_token, id_token, email, plan_type,
					enabled, websockets, password, mfa_code, expires_at, status, weight, proxy_url,
					cooldown_until, cooldown_reason,
					usage_primary_used_pct, usage_primary_reset_secs, usage_primary_window_mins,
					usage_secondary_used_pct, usage_secondary_reset_secs, usage_secondary_window_mins,
					usage_primary_over_secondary_pct, usage_reset_credits_available_count, usage_updated_at,
					created_at, updated_at
				) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`),
				a.ID, a.AccountID, a.RefreshToken, a.AccessToken, a.IDToken, a.Email, a.PlanType,
				boolToInt(a.Enabled), boolToInt(a.Websockets),
				a.Password, a.MFACode,
				nullTime(a.ExpiresAt), string(a.Status), a.EffectiveWeight(), a.ProxyUrl,
				nullTime(a.CooldownUntil), a.CooldownReason,
				usagePrimPct, usagePrimReset, usagePrimWin,
				usageSecPct, usageSecReset, usageSecWin,
				usagePriOverSec, usageResetCredits, usageUpdatedAt,
				sqliteTime(a.CreatedAt), sqliteTime(a.UpdatedAt),
			); err != nil {
				return fmt.Errorf("insert account %q: %w", a.AccountID, err)
			}
		}

		// Clear usage stats whose account no longer exists after full account replace.
		if _, err := tx.ExecContext(txCtx, `
			DELETE FROM codex_account_stats
			WHERE NOT EXISTS (
				SELECT 1 FROM codex_accounts WHERE codex_accounts.id = codex_account_stats.account_id
			)`); err != nil {
			return fmt.Errorf("clear orphan stats: %w", err)
		}

		return nil
	})
}

// --- Hot-path partial updates ---

func (s *SQLiteCodexAccountStore) UpdateTokens(ctx context.Context, accountID, accessToken, idToken, refreshToken string, expiresAt time.Time) error {
	accountID = strings.TrimSpace(accountID)
	if accountID == "" {
		return fmt.Errorf("account id is empty")
	}

	result, err := s.execWrite(ctx, `
		UPDATE codex_accounts SET
			access_token = ?, id_token = ?, refresh_token = ?, expires_at = ?, updated_at = ?
		WHERE id = ?`,
		accessToken, idToken, refreshToken, nullTime(expiresAt), sqliteTime(time.Now()), accountID)
	if err != nil {
		return err
	}

	rows, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("query rows affected: %w", err)
	}
	if rows == 0 {
		return fmt.Errorf("account not found for update: %s", accountID)
	}
	return nil
}

func (s *SQLiteCodexAccountStore) UpdateStatus(ctx context.Context, accountID string, status CodexAccountStatus) error {
	_, err := s.execWrite(ctx, `
		UPDATE codex_accounts SET status = ?, updated_at = ? WHERE id = ?`,
		string(status), sqliteTime(time.Now()), accountID)
	return err
}

func (s *SQLiteCodexAccountStore) UpdateCooldown(ctx context.Context, accountID string, until time.Time, reason string) error {
	_, err := s.execWrite(ctx, `
		UPDATE codex_accounts SET cooldown_until = ?, cooldown_reason = ?, updated_at = ? WHERE id = ?`,
		nullTime(until), reason, sqliteTime(time.Now()), accountID)
	return err
}

func (s *SQLiteCodexAccountStore) UpdateUsageSnapshot(ctx context.Context, accountID string, snapshot *CodexUsageSnapshot) error {
	if snapshot == nil {
		return nil
	}
	_, err := s.execWrite(ctx, `
		UPDATE codex_accounts SET
			usage_primary_used_pct = ?, usage_primary_reset_secs = ?, usage_primary_window_mins = ?,
			usage_secondary_used_pct = ?, usage_secondary_reset_secs = ?, usage_secondary_window_mins = ?,
			usage_primary_over_secondary_pct = ?,
			usage_reset_credits_available_count = CASE WHEN ? != 0 THEN ? ELSE usage_reset_credits_available_count END,
			usage_updated_at = ?,
			updated_at = ?
		WHERE id = ?`,
		snapshot.PrimaryUsedPercent, snapshot.PrimaryResetAfterSeconds, snapshot.PrimaryWindowMinutes,
		snapshot.SecondaryUsedPercent, snapshot.SecondaryResetAfterSeconds, snapshot.SecondaryWindowMinutes,
		snapshot.PrimaryOverSecondaryPercent,
		boolToInt(snapshot.ResetCreditsAvailable), snapshot.ResetCreditsAvailableCount, nullTime(snapshot.UpdatedAt),
		sqliteTime(time.Now()), accountID)
	return err
}

// --- Stats ---

func (s *SQLiteCodexAccountStore) InsertStat(ctx context.Context, stat *CodexAccountStat) error {
	if stat == nil {
		return nil
	}
	now := time.Now()
	if stat.Date == "" {
		stat.Date = now.Format("2006-01-02")
	}
	if stat.Hour < 0 {
		stat.Hour = now.Hour()
	}
	_, err := s.execWrite(ctx, `
		INSERT INTO codex_account_stats (
			account_id, account_email, model, date, hour,
			input_tokens, output_tokens, total_tokens,
			cached_tokens, cache_read_tokens, cache_creation_tokens, reasoning_tokens,
			status_code, status, error_type, duration_ms, ttft_ms,
			executor_type, requested_model, source, reasoning_effort, service_tier, response_service_tier,
			additional_model,
			primary_used_pct, secondary_used_pct, request_path
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		stat.AccountID, stat.AccountEmail, stat.Model, stat.Date, stat.Hour,
		stat.InputTokens, stat.OutputTokens, stat.TotalTokens,
		stat.CachedTokens, stat.CacheReadTokens, stat.CacheCreationTokens, stat.ReasoningTokens,
		stat.StatusCode, stat.Status, stat.ErrorType, stat.DurationMs, stat.TTFTMs,
		stat.ExecutorType, stat.RequestedModel, stat.Source, stat.ReasoningEffort, stat.ServiceTier, stat.ResponseServiceTier,
		boolToInt(stat.AdditionalModel),
		stat.PrimaryUsedPct, stat.SecondaryUsedPct, stat.RequestPath,
	)
	return err
}

func (s *SQLiteCodexAccountStore) GetStatsSummary(ctx context.Context, accountID string, timeRange string) (*CodexAccountStatsSummary, error) {
	dateCond := codexStatsDateCondition(timeRange)
	row := s.queryRowContext(ctx, fmt.Sprintf(`
		SELECT
			account_id,
			COALESCE(MAX(account_email), '') as account_email,
			SUM(CASE WHEN additional_model = 0 THEN 1 ELSE 0 END) as request_count,
			COALESCE(SUM(input_tokens), 0) as input_tokens,
			COALESCE(SUM(output_tokens), 0) as output_tokens,
			COALESCE(SUM(total_tokens), 0) as total_tokens,
			COALESCE(SUM(cached_tokens), 0) as cached_tokens,
			COALESCE(SUM(cache_read_tokens), 0) as cache_read_tokens,
			COALESCE(SUM(cache_creation_tokens), 0) as cache_creation_tokens,
			COALESCE(SUM(reasoning_tokens), 0) as reasoning_tokens,
			SUM(CASE WHEN additional_model = 0 AND (status_code >= 400 OR status = 'error') THEN 1 ELSE 0 END) as error_count,
			COALESCE(AVG(CASE WHEN additional_model = 0 THEN duration_ms END), 0) as avg_duration_ms
		FROM codex_account_stats
		WHERE account_id = ? AND %s
		GROUP BY account_id`, dateCond), accountID)

	var sum CodexAccountStatsSummary
	err := row.Scan(&sum.AccountID, &sum.AccountEmail, &sum.RequestCount,
		&sum.InputTokens, &sum.OutputTokens, &sum.TotalTokens,
		&sum.CachedTokens, &sum.CacheReadTokens, &sum.CacheCreationTokens, &sum.ReasoningTokens,
		&sum.ErrorCount, &sum.AvgDurationMs)
	if err == sql.ErrNoRows {
		return &CodexAccountStatsSummary{AccountID: accountID}, nil
	}
	if err != nil {
		return nil, err
	}
	return &sum, nil
}

func (s *SQLiteCodexAccountStore) GetStatsSummaryMap(ctx context.Context, accountIDs []string, timeRange string) (map[string]CodexAccountStatsSummary, error) {
	result := make(map[string]CodexAccountStatsSummary, len(accountIDs))
	if len(accountIDs) == 0 {
		return result, nil
	}

	uniqueIDs := make([]string, 0, len(accountIDs))
	seen := make(map[string]struct{}, len(accountIDs))
	for _, id := range accountIDs {
		id = strings.TrimSpace(id)
		if id == "" {
			continue
		}
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		uniqueIDs = append(uniqueIDs, id)
	}
	if len(uniqueIDs) == 0 {
		return result, nil
	}

	dateCond := codexStatsDateCondition(timeRange)
	placeholders := s.placeholders(len(uniqueIDs))
	query := fmt.Sprintf(`
		SELECT
			account_id,
			COALESCE(MAX(account_email), '') as account_email,
			SUM(CASE WHEN additional_model = 0 THEN 1 ELSE 0 END) as request_count,
			COALESCE(SUM(input_tokens), 0) as input_tokens,
			COALESCE(SUM(output_tokens), 0) as output_tokens,
			COALESCE(SUM(total_tokens), 0) as total_tokens,
			COALESCE(SUM(cached_tokens), 0) as cached_tokens,
			COALESCE(SUM(cache_read_tokens), 0) as cache_read_tokens,
			COALESCE(SUM(cache_creation_tokens), 0) as cache_creation_tokens,
			COALESCE(SUM(reasoning_tokens), 0) as reasoning_tokens,
			SUM(CASE WHEN additional_model = 0 AND (status_code >= 400 OR status = 'error') THEN 1 ELSE 0 END) as error_count,
			COALESCE(AVG(CASE WHEN additional_model = 0 THEN duration_ms END), 0) as avg_duration_ms
		FROM codex_account_stats
		WHERE account_id IN (%s) AND %s
		GROUP BY account_id`, placeholders, dateCond)

	args := make([]any, 0, len(uniqueIDs))
	for _, id := range uniqueIDs {
		args = append(args, id)
	}

	rows, err := s.queryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var sum CodexAccountStatsSummary
		if err := rows.Scan(&sum.AccountID, &sum.AccountEmail, &sum.RequestCount,
			&sum.InputTokens, &sum.OutputTokens, &sum.TotalTokens,
			&sum.CachedTokens, &sum.CacheReadTokens, &sum.CacheCreationTokens, &sum.ReasoningTokens,
			&sum.ErrorCount, &sum.AvgDurationMs); err != nil {
			return nil, err
		}
		result[sum.AccountID] = sum
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	for _, id := range uniqueIDs {
		if _, ok := result[id]; !ok {
			result[id] = CodexAccountStatsSummary{AccountID: id}
		}
	}
	return result, nil
}

func (s *SQLiteCodexAccountStore) GetAllStatsSummary(ctx context.Context, timeRange string) ([]CodexAccountStatsSummary, error) {
	dateCond := codexStatsDateCondition(timeRange)
	rows, err := s.queryContext(ctx, fmt.Sprintf(`
		SELECT
			account_id,
			COALESCE(MAX(account_email), '') as account_email,
			SUM(CASE WHEN additional_model = 0 THEN 1 ELSE 0 END) as request_count,
			COALESCE(SUM(input_tokens), 0) as input_tokens,
			COALESCE(SUM(output_tokens), 0) as output_tokens,
			COALESCE(SUM(total_tokens), 0) as total_tokens,
			COALESCE(SUM(cached_tokens), 0) as cached_tokens,
			COALESCE(SUM(cache_read_tokens), 0) as cache_read_tokens,
			COALESCE(SUM(cache_creation_tokens), 0) as cache_creation_tokens,
			COALESCE(SUM(reasoning_tokens), 0) as reasoning_tokens,
			SUM(CASE WHEN additional_model = 0 AND (status_code >= 400 OR status = 'error') THEN 1 ELSE 0 END) as error_count,
			COALESCE(AVG(CASE WHEN additional_model = 0 THEN duration_ms END), 0) as avg_duration_ms
		FROM codex_account_stats
		WHERE %s
		GROUP BY account_id
		ORDER BY request_count DESC`, dateCond))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []CodexAccountStatsSummary
	for rows.Next() {
		var sum CodexAccountStatsSummary
		if err := rows.Scan(&sum.AccountID, &sum.AccountEmail, &sum.RequestCount,
			&sum.InputTokens, &sum.OutputTokens, &sum.TotalTokens,
			&sum.CachedTokens, &sum.CacheReadTokens, &sum.CacheCreationTokens, &sum.ReasoningTokens,
			&sum.ErrorCount, &sum.AvgDurationMs); err != nil {
			return nil, err
		}
		result = append(result, sum)
	}
	return result, rows.Err()
}

func (s *SQLiteCodexAccountStore) DeleteStats(ctx context.Context, accountID string) error {
	_, err := s.execWrite(ctx, `DELETE FROM codex_account_stats WHERE account_id = ?`, accountID)
	return err
}

// --- Model prices and estimated cost ---

const codexModelPricesInitializedKey = "model_prices_initialized_v1"

var defaultCodexModelPrices = []CodexModelPrice{
	{Model: "gpt-5.6-sol", InputPer1M: 10, CachedInputPer1M: 1, CacheWritePer1M: 12.5, OutputPer1M: 60},
	{Model: "gpt-5.6-terra", InputPer1M: 5, CachedInputPer1M: 0.5, CacheWritePer1M: 6.25, OutputPer1M: 30},
	{Model: "gpt-5.6-luna", InputPer1M: 2, CachedInputPer1M: 0.2, CacheWritePer1M: 2.5, OutputPer1M: 12},
	{Model: "gpt-5.5", InputPer1M: 12.5, CachedInputPer1M: 1.25, CacheWritePer1M: 0, OutputPer1M: 75},
	{Model: "gpt-5.4", InputPer1M: 5, CachedInputPer1M: 0.5, CacheWritePer1M: 0, OutputPer1M: 30},
	{Model: "gpt-5.4-mini", InputPer1M: 1.5, CachedInputPer1M: 0.15, CacheWritePer1M: 0, OutputPer1M: 9},
}

func (s *SQLiteCodexAccountStore) initializeDefaultModelPrices(ctx context.Context) error {
	return s.withTx(ctx, func(txCtx context.Context, tx *sql.Tx) error {
		var marker string
		err := tx.QueryRowContext(txCtx, s.rebind(`SELECT value FROM codex_store_metadata WHERE meta_key = ?`), codexModelPricesInitializedKey).Scan(&marker)
		if err == nil {
			return nil
		}
		if !errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("read model price initialization marker: %w", err)
		}

		var count int
		if err := tx.QueryRowContext(txCtx, `SELECT COUNT(*) FROM codex_model_prices`).Scan(&count); err != nil {
			return fmt.Errorf("count model prices: %w", err)
		}
		if count == 0 {
			now := sqliteTime(time.Now())
			for _, price := range defaultCodexModelPrices {
				if _, err := tx.ExecContext(txCtx, s.rebind(`
					INSERT INTO codex_model_prices (
						model, input_per_1m, cached_input_per_1m, cache_write_per_1m, output_per_1m, updated_at
					) VALUES (?, ?, ?, ?, ?, ?)`),
					price.Model, price.InputPer1M, price.CachedInputPer1M, price.CacheWritePer1M, price.OutputPer1M, now); err != nil {
					return fmt.Errorf("insert default model price %q: %w", price.Model, err)
				}
			}
		}

		_, err = tx.ExecContext(txCtx, s.rebind(`
			INSERT INTO codex_store_metadata (meta_key, value, updated_at) VALUES (?, ?, ?)`),
			codexModelPricesInitializedKey, "1", sqliteTime(time.Now()))
		if err != nil {
			return fmt.Errorf("write model price initialization marker: %w", err)
		}
		return nil
	})
}

func validateCodexModelPrices(prices []CodexModelPrice) ([]CodexModelPrice, error) {
	normalized := make([]CodexModelPrice, len(prices))
	seen := make(map[string]struct{}, len(prices))
	for i, price := range prices {
		price.Model = strings.TrimSpace(price.Model)
		if price.Model == "" {
			return nil, fmt.Errorf("model price at index %d has an empty model", i)
		}
		if _, ok := seen[price.Model]; ok {
			return nil, fmt.Errorf("duplicate model price: %s", price.Model)
		}
		seen[price.Model] = struct{}{}
		for _, amount := range []float64{price.InputPer1M, price.CachedInputPer1M, price.CacheWritePer1M, price.OutputPer1M} {
			if math.IsNaN(amount) || math.IsInf(amount, 0) || amount < 0 {
				return nil, fmt.Errorf("model price %q contains an invalid amount", price.Model)
			}
		}
		normalized[i] = price
	}
	return normalized, nil
}

func (s *SQLiteCodexAccountStore) ListModelPrices(ctx context.Context) ([]CodexModelPrice, error) {
	rows, err := s.queryContext(ctx, `
		SELECT model, input_per_1m, cached_input_per_1m, cache_write_per_1m, output_per_1m, updated_at
		FROM codex_model_prices
		ORDER BY model`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	prices := make([]CodexModelPrice, 0)
	for rows.Next() {
		var price CodexModelPrice
		var updatedAt any
		if err := rows.Scan(&price.Model, &price.InputPer1M, &price.CachedInputPer1M, &price.CacheWritePer1M, &price.OutputPer1M, &updatedAt); err != nil {
			return nil, err
		}
		if parsed, ok := parseSQLiteTime(updatedAt); ok {
			price.UpdatedAt = parsed
		}
		prices = append(prices, price)
	}
	return prices, rows.Err()
}

func (s *SQLiteCodexAccountStore) ReplaceModelPrices(ctx context.Context, prices []CodexModelPrice) ([]CodexModelPrice, error) {
	normalized, err := validateCodexModelPrices(prices)
	if err != nil {
		return nil, err
	}

	if err := s.withTx(ctx, func(txCtx context.Context, tx *sql.Tx) error {
		if _, err := tx.ExecContext(txCtx, `DELETE FROM codex_model_prices`); err != nil {
			return err
		}
		now := sqliteTime(time.Now())
		for _, price := range normalized {
			if _, err := tx.ExecContext(txCtx, s.rebind(`
				INSERT INTO codex_model_prices (
					model, input_per_1m, cached_input_per_1m, cache_write_per_1m, output_per_1m, updated_at
				) VALUES (?, ?, ?, ?, ?, ?)`),
				price.Model, price.InputPer1M, price.CachedInputPer1M, price.CacheWritePer1M, price.OutputPer1M, now); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return nil, err
	}
	return s.ListModelPrices(ctx)
}

func (s *SQLiteCodexAccountStore) GetTodayEstimatedCostMap(ctx context.Context, accountIDs []string) (map[string]*float64, error) {
	result := make(map[string]*float64, len(accountIDs))
	uniqueIDs := make([]string, 0, len(accountIDs))
	seen := make(map[string]struct{}, len(accountIDs))
	for _, accountID := range accountIDs {
		accountID = strings.TrimSpace(accountID)
		if accountID == "" {
			continue
		}
		if _, ok := seen[accountID]; ok {
			continue
		}
		seen[accountID] = struct{}{}
		uniqueIDs = append(uniqueIDs, accountID)
	}
	if len(uniqueIDs) == 0 {
		return result, nil
	}

	prices, err := s.ListModelPrices(ctx)
	if err != nil {
		return nil, err
	}
	if len(prices) == 0 {
		for _, accountID := range uniqueIDs {
			result[accountID] = nil
		}
		return result, nil
	}
	priceByModel := make(map[string]CodexModelPrice, len(prices))
	for _, price := range prices {
		priceByModel[price.Model] = price
	}

	for _, accountID := range uniqueIDs {
		zero := 0.0
		result[accountID] = &zero
	}
	costs := make(map[string]float64, len(uniqueIDs))
	missingPrice := make(map[string]bool, len(uniqueIDs))
	placeholders := s.placeholders(len(uniqueIDs))
	query := fmt.Sprintf(`
		SELECT account_id, model,
			COALESCE(SUM(input_tokens), 0),
			COALESCE(SUM(cache_read_tokens), 0),
			COALESCE(SUM(cache_creation_tokens), 0),
			COALESCE(SUM(output_tokens), 0)
		FROM codex_account_stats
		WHERE account_id IN (%s) AND %s
		GROUP BY account_id, model`, placeholders, codexStatsDateCondition("today"))
	args := make([]any, 0, len(uniqueIDs))
	for _, accountID := range uniqueIDs {
		args = append(args, accountID)
	}
	rows, err := s.queryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		var accountID, model string
		var inputTokens, cacheReadTokens, cacheCreationTokens, outputTokens int64
		if err := rows.Scan(&accountID, &model, &inputTokens, &cacheReadTokens, &cacheCreationTokens, &outputTokens); err != nil {
			return nil, err
		}
		if inputTokens == 0 && cacheReadTokens == 0 && cacheCreationTokens == 0 && outputTokens == 0 {
			continue
		}
		price, ok := priceByModel[strings.TrimSpace(model)]
		if !ok {
			missingPrice[accountID] = true
			continue
		}
		uncachedInput := inputTokens - cacheReadTokens - cacheCreationTokens
		if uncachedInput < 0 {
			uncachedInput = 0
		}
		costs[accountID] += float64(uncachedInput)*price.InputPer1M/1_000_000 +
			float64(cacheReadTokens)*price.CachedInputPer1M/1_000_000 +
			float64(cacheCreationTokens)*price.CacheWritePer1M/1_000_000 +
			float64(outputTokens)*price.OutputPer1M/1_000_000
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	for _, accountID := range uniqueIDs {
		if missingPrice[accountID] {
			result[accountID] = nil
			continue
		}
		cost := costs[accountID]
		result[accountID] = &cost
	}
	return result, nil
}

// --- Helpers ---

func sqliteTime(t time.Time) string {
	return t.Format(time.RFC3339Nano)
}

func nullTime(t time.Time) any {
	if t.IsZero() {
		return nil
	}
	return sqliteTime(t)
}

type rowScanner interface {
	Scan(dest ...any) error
}

func scanFromScanner(s rowScanner) (*CodexAccount, error) {
	var a CodexAccount
	var expiresAt, cooldownUntil, usageUpdatedAt, createdAt, updatedAt any
	var status string
	var enabled, websockets int
	var usagePrimPct, usageSecPct, usagePriOverSec float64
	var usagePrimReset, usagePrimWin, usageSecReset, usageSecWin, usageResetCredits int

	err := s.Scan(
		&a.ID, &a.AccountID, &a.RefreshToken, &a.AccessToken, &a.IDToken, &a.Email, &a.PlanType,
		&enabled, &websockets, &a.Password, &a.MFACode,
		&expiresAt, &status, &a.Weight, &a.ProxyUrl,
		&cooldownUntil, &a.CooldownReason,
		&usagePrimPct, &usagePrimReset, &usagePrimWin,
		&usageSecPct, &usageSecReset, &usageSecWin,
		&usagePriOverSec, &usageResetCredits, &usageUpdatedAt,
		&createdAt, &updatedAt,
	)
	if err != nil {
		return nil, err
	}

	a.Status = CodexAccountStatus(status)
	a.Enabled = enabled != 0
	a.Websockets = websockets != 0
	if t, ok := parseSQLiteTime(expiresAt); ok {
		a.ExpiresAt = t
	}
	if t, ok := parseSQLiteTime(cooldownUntil); ok {
		a.CooldownUntil = t
	}
	if t, ok := parseSQLiteTime(createdAt); ok {
		a.CreatedAt = t
	}
	if t, ok := parseSQLiteTime(updatedAt); ok {
		a.UpdatedAt = t
	}
	usageUpdatedAtTime, hasUsageUpdatedAt := parseSQLiteTime(usageUpdatedAt)
	if hasUsageUpdatedAt || usagePrimPct > 0 || usageSecPct > 0 || usageResetCredits > 0 {
		a.CodexUsage = &CodexUsageSnapshot{
			PrimaryUsedPercent:          usagePrimPct,
			PrimaryResetAfterSeconds:    usagePrimReset,
			PrimaryWindowMinutes:        usagePrimWin,
			SecondaryUsedPercent:        usageSecPct,
			SecondaryResetAfterSeconds:  usageSecReset,
			SecondaryWindowMinutes:      usageSecWin,
			PrimaryOverSecondaryPercent: usagePriOverSec,
			ResetCreditsAvailableCount:  usageResetCredits,
			ResetCreditsAvailable:       usageResetCredits > 0,
		}
		if hasUsageUpdatedAt {
			a.CodexUsage.UpdatedAt = usageUpdatedAtTime
		}
	}
	return &a, nil
}

func scanLegacyAccount(rows *sql.Rows) (*CodexAccount, error) {
	var a CodexAccount
	var expiresAt, cooldownUntil, usageUpdatedAt, createdAt, updatedAt any
	var status string
	var enabled, websockets int
	var usagePrimPct, usageSecPct, usagePriOverSec float64
	var usagePrimReset, usagePrimWin, usageSecReset, usageSecWin, usageResetCredits int

	err := rows.Scan(
		&a.AccountID, &a.RefreshToken, &a.AccessToken, &a.IDToken, &a.Email, &a.PlanType,
		&enabled, &websockets, &a.Password, &a.MFACode,
		&expiresAt, &status, &a.Weight, &a.ProxyUrl,
		&cooldownUntil, &a.CooldownReason,
		&usagePrimPct, &usagePrimReset, &usagePrimWin,
		&usageSecPct, &usageSecReset, &usageSecWin,
		&usagePriOverSec, &usageResetCredits, &usageUpdatedAt,
		&createdAt, &updatedAt,
	)
	if err != nil {
		return nil, err
	}
	a.Status = CodexAccountStatus(status)
	a.Enabled = enabled != 0
	a.Websockets = websockets != 0
	if t, ok := parseSQLiteTime(expiresAt); ok {
		a.ExpiresAt = t
	}
	if t, ok := parseSQLiteTime(cooldownUntil); ok {
		a.CooldownUntil = t
	}
	if t, ok := parseSQLiteTime(createdAt); ok {
		a.CreatedAt = t
	}
	if t, ok := parseSQLiteTime(updatedAt); ok {
		a.UpdatedAt = t
	}
	usageUpdatedAtTime, hasUsageUpdatedAt := parseSQLiteTime(usageUpdatedAt)
	if hasUsageUpdatedAt || usagePrimPct > 0 || usageSecPct > 0 || usageResetCredits > 0 {
		a.CodexUsage = &CodexUsageSnapshot{
			PrimaryUsedPercent:          usagePrimPct,
			PrimaryResetAfterSeconds:    usagePrimReset,
			PrimaryWindowMinutes:        usagePrimWin,
			SecondaryUsedPercent:        usageSecPct,
			SecondaryResetAfterSeconds:  usageSecReset,
			SecondaryWindowMinutes:      usageSecWin,
			PrimaryOverSecondaryPercent: usagePriOverSec,
			ResetCreditsAvailableCount:  usageResetCredits,
			ResetCreditsAvailable:       usageResetCredits > 0,
		}
		if hasUsageUpdatedAt {
			a.CodexUsage.UpdatedAt = usageUpdatedAtTime
		}
	}
	return &a, nil
}

func parseSQLiteTime(value any) (time.Time, bool) {
	switch v := value.(type) {
	case nil:
		return time.Time{}, false
	case time.Time:
		return v, !v.IsZero()
	case string:
		return parseSQLiteTimeString(v)
	case []byte:
		return parseSQLiteTimeString(string(v))
	default:
		return time.Time{}, false
	}
}

func parseSQLiteTimeString(value string) (time.Time, bool) {
	value = strings.TrimSpace(value)
	if value == "" {
		return time.Time{}, false
	}
	formats := []string{
		time.RFC3339Nano,
		time.RFC3339,
		"2006-01-02 15:04:05.999999999-07:00",
		"2006-01-02T15:04:05.999999999-07:00",
		"2006-01-02 15:04:05.999999999 -0700 MST",
		"2006-01-02 15:04:05.999999999 -0700 -0700",
		"2006-01-02 15:04:05 -0700 -0700",
		"2006-01-02 15:04:05.999999999",
		"2006-01-02T15:04:05.999999999",
		"2006-01-02 15:04",
		"2006-01-02T15:04",
		"2006-01-02",
	}
	for _, format := range formats {
		if t, err := time.Parse(format, value); err == nil {
			return t, true
		}
	}
	return time.Time{}, false
}

func scanAccount(rows *sql.Rows) (*CodexAccount, error) {
	return scanFromScanner(rows)
}

func scanAccountRow(row *sql.Row) (*CodexAccount, error) {
	a, err := scanFromScanner(row)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	return a, err
}

func boolToInt(v bool) int {
	if v {
		return 1
	}
	return 0
}

func codexStatsDateCondition(timeRange string) string {
	now := time.Now()
	switch timeRange {
	case "today":
		return fmt.Sprintf("date = '%s'", now.Format("2006-01-02"))
	case "yesterday":
		return fmt.Sprintf("date = '%s'", now.AddDate(0, 0, -1).Format("2006-01-02"))
	case "week":
		return fmt.Sprintf("date >= '%s'", now.AddDate(0, 0, -int(now.Weekday())).Format("2006-01-02"))
	case "month":
		return fmt.Sprintf("date >= '%s'", time.Date(now.Year(), now.Month(), 1, 0, 0, 0, 0, now.Location()).Format("2006-01-02"))
	default:
		return "1=1"
	}
}
