// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {proxy} from '../models';
import {storage} from '../models';
import {statsdb} from '../models';

export function ClearTokenStats(arg1:string):Promise<void>;

export function DeleteEndpoint(arg1:number):Promise<void>;

export function DeleteVendor(arg1:number):Promise<void>;

export function FetchModels(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetActiveEndpoint(arg1:string):Promise<main.EndpointInfo>;

export function GetAllEndpoints():Promise<Array<main.EndpointInfo>>;

export function GetCLIConfigDirs():Promise<main.CLIConfigDirs>;

export function GetClaudeConfig():Promise<main.CLIConfigResult>;

export function GetCodexConfig():Promise<main.CLIConfigResult>;

export function GetComputerName():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetEndpointsByType(arg1:string):Promise<Array<main.EndpointInfo>>;

export function GetEndpointsByVendorID(arg1:number):Promise<Array<main.EndpointInfo>>;

export function GetFullConfig():Promise<main.FullConfig>;

export function GetInterfaceTypes():Promise<Array<string>>;

export function GetLanguage():Promise<string>;

export function GetLocalIPs():Promise<Array<main.LocalIPInfo>>;

export function GetLogDetail(arg1:string):Promise<main.RequestLogDetailInfo>;

export function GetPort():Promise<number>;

export function GetProxyStatus():Promise<Record<string, any>>;

export function GetRecentLogs():Promise<Array<main.RequestLogInfo>>;

export function GetSettings():Promise<main.Settings>;

export function GetStatsByInterfaceType(arg1:string):Promise<Array<main.InterfaceTypeStatsSummaryInfo>>;

export function GetTokenStats():Promise<Array<main.TokenStatsInfo>>;

export function GetTokenStatsByTimeRange(arg1:string):Promise<Array<main.VendorStatsSummaryInfo>>;

export function GetTokenStatsForEndpoint(arg1:string):Promise<main.TokenStatsInfo>;

export function GetTransformers():Promise<Record<string, Array<string>>>;

export function GetVendors():Promise<Array<main.VendorInfo>>;

export function GetWebSocketURL():Promise<string>;

export function ProcessClaudeConfig(arg1:string):Promise<string>;

export function ProcessClaudeConfigWithIP(arg1:string,arg2:string):Promise<string>;

export function ProcessCodexConfig(arg1:string,arg2:string):Promise<main.ProcessCodexConfigResult>;

export function ProcessCodexConfigWithIP(arg1:string,arg2:string,arg3:string):Promise<main.ProcessCodexConfigResult>;

export function ReloadConfig():Promise<void>;

export function SaveCLIConfigDirs(arg1:main.CLIConfigDirs):Promise<void>;

export function SaveClaudeConfig(arg1:string):Promise<void>;

export function SaveCodexConfig(arg1:string,arg2:string):Promise<void>;

export function SaveEndpointData(arg1:main.EndpointInput):Promise<main.EndpointInfo>;

export function SaveFullConfig(arg1:main.FullConfig):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SaveVendor(arg1:main.VendorInfo):Promise<main.VendorInfo>;

export function SetActiveEndpoint(arg1:string,arg2:number):Promise<void>;

export function SetConfigLoader(arg1:config.ConfigLoader):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function SetProxyServer(arg1:proxy.ProxyServer):Promise<void>;

export function SetRouter(arg1:proxy.DefaultRouter):Promise<void>;

export function SetStorage(arg1:storage.Storage):Promise<void>;

export function SetVendorStats(arg1:statsdb.SQLiteVendorStatsStore):Promise<void>;

export function SetWSHub(arg1:proxy.WSHub):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TestEndpoint(arg1:number):Promise<string>;

export function TestEndpointWithParams(arg1:main.TestEndpointParams):Promise<string>;

export function ToggleEndpointEnabled(arg1:number,arg2:boolean):Promise<void>;

export function WebDAVCopy(arg1:main.WebDAVRequestInput):Promise<proxy.WebDAVResponse>;

export function WebDAVDelete(arg1:main.WebDAVRequestInput):Promise<proxy.WebDAVResponse>;

export function WebDAVGet(arg1:main.WebDAVRequestInput):Promise<proxy.WebDAVResponse>;

export function WebDAVList(arg1:main.WebDAVRequestInput):Promise<proxy.WebDAVResponse>;

export function WebDAVMkcol(arg1:main.WebDAVRequestInput):Promise<proxy.WebDAVResponse>;

export function WebDAVMove(arg1:main.WebDAVRequestInput):Promise<proxy.WebDAVResponse>;

export function WebDAVProxyRequest(arg1:main.WebDAVRequestInput):Promise<proxy.WebDAVResponse>;

export function WebDAVPut(arg1:main.WebDAVRequestInput):Promise<proxy.WebDAVResponse>;
