// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTokenStats(arg1) {
  return window['go']['main']['App']['ClearTokenStats'](arg1);
}

export function DeleteEndpoint(arg1) {
  return window['go']['main']['App']['DeleteEndpoint'](arg1);
}

export function DeleteVendor(arg1) {
  return window['go']['main']['App']['DeleteVendor'](arg1);
}

export function FetchModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchModels'](arg1, arg2, arg3);
}

export function GetActiveEndpoint(arg1) {
  return window['go']['main']['App']['GetActiveEndpoint'](arg1);
}

export function GetAllEndpoints() {
  return window['go']['main']['App']['GetAllEndpoints']();
}

export function GetCLIConfigDirs() {
  return window['go']['main']['App']['GetCLIConfigDirs']();
}

export function GetClaudeConfig() {
  return window['go']['main']['App']['GetClaudeConfig']();
}

export function GetCodexConfig() {
  return window['go']['main']['App']['GetCodexConfig']();
}

export function GetComputerName() {
  return window['go']['main']['App']['GetComputerName']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetEndpointsByType(arg1) {
  return window['go']['main']['App']['GetEndpointsByType'](arg1);
}

export function GetEndpointsByVendorID(arg1) {
  return window['go']['main']['App']['GetEndpointsByVendorID'](arg1);
}

export function GetFullConfig() {
  return window['go']['main']['App']['GetFullConfig']();
}

export function GetInterfaceTypes() {
  return window['go']['main']['App']['GetInterfaceTypes']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetLogDetail(arg1) {
  return window['go']['main']['App']['GetLogDetail'](arg1);
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRecentLogs() {
  return window['go']['main']['App']['GetRecentLogs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatsByInterfaceType(arg1) {
  return window['go']['main']['App']['GetStatsByInterfaceType'](arg1);
}

export function GetTokenStats() {
  return window['go']['main']['App']['GetTokenStats']();
}

export function GetTokenStatsByTimeRange(arg1) {
  return window['go']['main']['App']['GetTokenStatsByTimeRange'](arg1);
}

export function GetTokenStatsForEndpoint(arg1) {
  return window['go']['main']['App']['GetTokenStatsForEndpoint'](arg1);
}

export function GetTransformers() {
  return window['go']['main']['App']['GetTransformers']();
}

export function GetVendors() {
  return window['go']['main']['App']['GetVendors']();
}

export function GetWebSocketURL() {
  return window['go']['main']['App']['GetWebSocketURL']();
}

export function ProcessClaudeConfig(arg1) {
  return window['go']['main']['App']['ProcessClaudeConfig'](arg1);
}

export function ProcessClaudeConfigWithIP(arg1, arg2) {
  return window['go']['main']['App']['ProcessClaudeConfigWithIP'](arg1, arg2);
}

export function ProcessCodexConfig(arg1, arg2) {
  return window['go']['main']['App']['ProcessCodexConfig'](arg1, arg2);
}

export function ProcessCodexConfigWithIP(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessCodexConfigWithIP'](arg1, arg2, arg3);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SaveCLIConfigDirs(arg1) {
  return window['go']['main']['App']['SaveCLIConfigDirs'](arg1);
}

export function SaveClaudeConfig(arg1) {
  return window['go']['main']['App']['SaveClaudeConfig'](arg1);
}

export function SaveCodexConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveCodexConfig'](arg1, arg2);
}

export function SaveEndpointData(arg1) {
  return window['go']['main']['App']['SaveEndpointData'](arg1);
}

export function SaveFullConfig(arg1) {
  return window['go']['main']['App']['SaveFullConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveVendor(arg1) {
  return window['go']['main']['App']['SaveVendor'](arg1);
}

export function SetActiveEndpoint(arg1, arg2) {
  return window['go']['main']['App']['SetActiveEndpoint'](arg1, arg2);
}

export function SetConfigLoader(arg1) {
  return window['go']['main']['App']['SetConfigLoader'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function SetProxyServer(arg1) {
  return window['go']['main']['App']['SetProxyServer'](arg1);
}

export function SetRouter(arg1) {
  return window['go']['main']['App']['SetRouter'](arg1);
}

export function SetStorage(arg1) {
  return window['go']['main']['App']['SetStorage'](arg1);
}

export function SetVendorStats(arg1) {
  return window['go']['main']['App']['SetVendorStats'](arg1);
}

export function SetWSHub(arg1) {
  return window['go']['main']['App']['SetWSHub'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestEndpoint(arg1) {
  return window['go']['main']['App']['TestEndpoint'](arg1);
}

export function TestEndpointWithParams(arg1) {
  return window['go']['main']['App']['TestEndpointWithParams'](arg1);
}

export function ToggleEndpointEnabled(arg1, arg2) {
  return window['go']['main']['App']['ToggleEndpointEnabled'](arg1, arg2);
}

export function WebDAVCopy(arg1) {
  return window['go']['main']['App']['WebDAVCopy'](arg1);
}

export function WebDAVDelete(arg1) {
  return window['go']['main']['App']['WebDAVDelete'](arg1);
}

export function WebDAVGet(arg1) {
  return window['go']['main']['App']['WebDAVGet'](arg1);
}

export function WebDAVList(arg1) {
  return window['go']['main']['App']['WebDAVList'](arg1);
}

export function WebDAVMkcol(arg1) {
  return window['go']['main']['App']['WebDAVMkcol'](arg1);
}

export function WebDAVMove(arg1) {
  return window['go']['main']['App']['WebDAVMove'](arg1);
}

export function WebDAVProxyRequest(arg1) {
  return window['go']['main']['App']['WebDAVProxyRequest'](arg1);
}

export function WebDAVPut(arg1) {
  return window['go']['main']['App']['WebDAVPut'](arg1);
}
